In [262]:
#https://neurostars.org/t/extracting-individual-transforms-from-composite-h5-files-fmriprep/2215/5
#CompositeTransformUtil et CompositeTransformUtil
#https://sourceforge.net/p/advants/discussion/840261/thread/8708b367/?limit=25

import h5py
from nipype.pipeline import engine as pe
from nipype.interfaces import utility as niu, fsl, c3
import nibabel as nib
import numpy as np
import os

DIR='''/NAS/tupac/protocoles/prodigy2/BIDS_process/fmriprep/sub-01016A6XPRODIGY20171205/anat/'''
NAME='''sub-01016A6XPRODIGY20171205_T1w_space-MNI152NLin2009cAsym_target-T1w_warp'''
EXT='''.h5'''
FILE_NAME=NAME+EXT
trans1 = h5py.File(os.path.join(DIR,FILE_NAME))

cpt=0
while cpt<len(trans1["TransformGroup"]) :
    if len(trans1["TransformGroup"][str(cpt)]) > 2 :    
        print "OK"
        if len(trans1["TransformGroup"][str(cpt)]["TranformParameters"])>12:
            dataset = np.array(trans1["TransformGroup"][str(cpt)]["TranformParameters"],dtype=np.int16)
            dataset2 = np.array(trans1["TransformGroup"][str(cpt)]["TranformFixedParameters"],dtype=np.int16)
            datasetr = np.reshape(dataset,(dataset2[0],dataset2[1],dataset2[2],3))
            affine = np.eye(4)
            affine[0,3]=-1*dataset2[3]
            affine[1,3]=-1*dataset2[4]
            affine[2,3]=dataset2[5]
            img = nib.Nifti1Image(datasetr,affine)
            img.header.set_xyzt_units("mm","sec")
            NEW_NAME=NAME+"_"+str(cpt)+".nii.gz"
            print(os.path.join(DIR,NEW_NAME))
            nib.save(img,os.path.join(DIR,NEW_NAME))
        else:
            mat = np.eye(4)
            print(mat[1:4,1:4])
            mat = np.reshape(trans1["TransformGroup"][str(cpt)]["TranformParameters"].value,(3,4), order='F')
    cpt = cpt + 1

OK
/NAS/tupac/protocoles/prodigy2/BIDS_process/fmriprep/sub-01016A6XPRODIGY20171205/anat/sub-01016A6XPRODIGY20171205_T1w_space-MNI152NLin2009cAsym_target-T1w_warp_1.nii.gz
OK
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[  1.02967143   0.06095668  -0.05948336   1.10736251]
 [ -0.06071652   1.02901053   0.37201247  25.08222771]
 [  0.0612592   -0.22722909   1.14701247 -31.06534576]]


In [251]:
x = iter(trans1["TransformGroup"])
print(dataset2[:])
print(dataset2[3:])
print(len(dataset2[6:]))
print(np.eye(4))
print(np.reshape(dataset2[6:],(3,4)))
print(np.reshape(dataset2[6:],(4,3)))
affine = np.eye(4)
print affine
print affine[0,0]
print affine[1,1]
print affine[2,2]
print affine[3,3]
from nipy import Image, vox2mni
print(vox2mni(np.eye(4)))

[193 229 193  96 132 -78   1   1   1  -1   0   0   0  -1   0   0   0   1]
[ 96 132 -78   1   1   1  -1   0   0   0  -1   0   0   0   1]
12
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1  1  1 -1]
 [ 0  0  0 -1]
 [ 0  0  0  1]]
[[ 1  1  1]
 [-1  0  0]
 [ 0 -1  0]
 [ 0  0  1]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
1.0
1.0
1.0
1.0


ImportError: No module named nipy

In [216]:
print(trans1["TransformGroup"]['1'])
print(trans1["TransformGroup"]['1']["TranformParameters"].value)
print(trans1["TransformGroup"]['1']["TranformFixedParameters"].value)
print(trans1["TransformGroup"]['2']["TranformParameters"].value)
print(trans1["TransformGroup"]['2']["TranformFixedParameters"].value)

<HDF5 group "/TransformGroup/1" (3 members)>
[ 0.  0.  0. ...,  0.  0.  0.]
[ 193.  229.  193.   96.  132.  -78.    1.    1.    1.   -1.    0.    0.
    0.   -1.    0.    0.    0.    1.]
[  1.02967143  -0.06071652   0.0612592    0.06095668   1.02901053
  -0.22722909  -0.05948336   0.37201247   1.14701247   1.10736251
  25.08222771 -31.06534576]
[  0.23592858  21.99948692   9.74520206]


In [96]:
for TransformGroup in trans1.keys :
    echo transform
#list(trans1.get('TransformGroup/1/TranformFixedParameters'))

SyntaxError: invalid syntax (<ipython-input-96-e42efc38570f>, line 2)

In [5]:
trans2 = h5py.File(DIR+'sub-01016A6XPRODIGY20171205_T1w_target-MNI152NLin2009cAsym_warp.h5')
print len(trans1['TransformGroup']['1']['TranformParameters'].value)
print len(trans1['TransformGroup']['2']['TranformParameters'].value)
print trans1['TransformGroup']['2']['TranformParameters'].value
print trans1['TransformGroup']['1']['TranformParameters'].value

25590063
12
[  1.02967143  -0.06071652   0.0612592    0.06095668   1.02901053
  -0.22722909  -0.05948336   0.37201247   1.14701247   1.10736251
  25.08222771 -31.06534576]
[ 0.  0.  0. ...,  0.  0.  0.]


In [6]:
print len(trans2['TransformGroup']['1']['TranformParameters'].value)
print len(trans2['TransformGroup']['2']['TranformParameters'].value)
print trans2['TransformGroup']['2']['TranformParameters'].value
print trans2['TransformGroup']['1']['TranformParameters'].value

12
25590063
[ 0.  0.  0. ...,  0.  0.  0.]
[  0.96483928   0.07050942  -0.03756152  -0.04302496   0.90371394
   0.18132845   0.06399032  -0.28944647   0.81107199  -4.00382614
 -16.98649406  32.3853302 ]


In [43]:
dataset = np.array(trans1)
dataset1 = np.array(trans1["TransformGroup"]['1'])
dataset2 = np.array(trans1["TransformGroup"]['1']["TranformParameters"],dtype=np.int16)


[u'HDFVersion' u'ITKVersion' u'OSName' u'OSVersion' u'TransformGroup']
[u'TranformFixedParameters' u'TranformParameters' u'TransformType']
[0 0 0 ..., 0 0 0]


In [248]:
print (img)

<class 'nibabel.nifti1.Nifti1Image'>
data shape (193, 229, 193, 3)
affine: 
[[   1.    0.    0.  -96.]
 [   0.    1.    0. -132.]
 [   0.    0.    1.  -78.]
 [   0.    0.    0.    1.]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : 
db_name         : 
extents         : 0
session_error   : 0
regular         : 
dim_info        : 0
dim             : [  4 193 229 193   3   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [ 1.  1.  1.  1.  1.  1.  1.  1.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : 
aux_file        : 
qform_code      : unknown
sform_code      : aligned


In [217]:
#from nipype.interfaces import fsl
#flt=fsl.Info()
ima = nib.load(DIR+'''00_sub-01016A6XPRODIGY20171205_T1w_space-MNI152NLin2009cAsym_target-T1w_warp_DisplacementFieldTransform.nii.gz''')
print(ima)

<class 'nibabel.nifti1.Nifti1Image'>
data shape (193, 229, 193, 1, 3)
affine: 
[[   1.    0.    0.  -96.]
 [   0.    1.    0. -132.]
 [   0.    0.    1.  -78.]
 [   0.    0.    0.    1.]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : 
db_name         : 
extents         : 0
session_error   : 0
regular         : r
dim_info        : 0
dim             : [  5 193 229 193   1   3   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : vector
datatype        : float64
bitpix          : 64
slice_start     : 0
pixdim          : [ 1.  1.  1.  1.  0.  0.  0.  0.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 2
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : 
aux_file        : 
qform_code      : scanner
sform_code      : u

In [38]:
c3.C3dAffineTool(fsl2ras=True, itk_transform=True)
fsl2itk_inv = pe.Node(c3.C3dAffineTool(fsl2ras=True, itk_transform=True),name='fsl2itk_inv', mem_gb=1)
print type(fsl2itk_inv)

<class 'nipype.pipeline.engine.nodes.Node'>


In [43]:
c3. absolute_import('''/NAS/tupac/protocoles/prodigy2/BIDS_process/fmriprep/sub-01016A6XPRODIGY20171205/anat/sub-01016A6XPRODIGY20171205_T1w_space-MNI152NLin2009cAsym_target-T1w_warp.h5''')

AttributeError: _Feature instance has no __call__ method

In [ ]:
c3 = c3.C3d()
c3.inputs.in_file = '''/NAS/tupac/protocoles/prodigy2/BIDS_process/fmriprep/sub-01016A6XPRODIGY20171205/anat/sub-01016A6XPRODIGY20171205_T1w_space-MNI152NLin2009cAsym_target-T1w_warp.h5'''
#c3.inputs.pix_type = "short"
c3.inputs.out_file = '''/NAS/tupac/protocoles/prodigy2/BIDS_process/fmriprep/sub-01016A6XPRODIGY20171205/anat/sub-01016A6XPRODIGY20171205_T1w_space-MNI152NLin2009cAsym_target-T1w_warp.nii.gz'''
c3.cmdline

In [266]:
import pkg_resources
print(pkg_resources.pkgutil)

<module 'pkgutil' from '/home/global/anaconda2/lib/python2.7/pkgutil.pyc'>
