In [25]:
import nibabel as nib
import os, sys, re
import numpy as np
from dipy.io.image import load_nifti, save_nifti
import matplotlib.pyplot as plt
from nipype.utils import NUMPY_MMAP
import nibabel.freesurfer.io.read_morph_data


In [60]:
data1, affine1 = load_nifti("/tmp/1528819594/WM.nii.gz")
nii = nib.load("/NAS/tupac/protocoles/healthy_volunteers/FS53/T01S01/mri/aseg.mgz", mmap=NUMPY_MMAP)
#hdr = nii.header
#voxdims = hdr.get_zooms()
#datadims = hdr.get_data_shape()
#print([(datadims[0]), (datadims[1]), (datadims[2])])
#print([float(voxdims[0]), float(voxdims[1]), float(voxdims[2])])

data2 = nii.get_data()
print(data2.dtype)
print(data1.dtype)
print(data2.shape)
print(data1.shape)

data3=data1
for i in [24, 28,30,31,60,62,63,72,85,251,252,253,254,255] :
    data3[data2==i]=i

save_nifti("/tmp/1528819594/couloucoucou.nii.gz",data3,affine1)

uint8
float32
(256, 256, 256)
(256, 256, 256)


In [225]:
labVB,scalarVB = nib.freesurfer.io.read_label("/NAS/tupac/romain/FS_VolBrain/FS60/bibiNew/label/lh.cortex.label",True)
print(labVB)
print(type(labVB))
print(labVB.shape)
print(scalarVB)

[     0      1      2 ..., 151017 151018 151019]
<type 'numpy.ndarray'>
(143873,)
[ 0.  0.  0. ...,  0.  0.  0.]


In [222]:
coordsVB1,facesVB1,volume_infoVB1,create_stampVB1 = nib.freesurfer.io.read_geometry("/NAS/tupac/romain/FS_VolBrain/FS60/bibiNew/surf//lh.white",True,True)
print(coordsVB1.shape)
print(coordsVB1)
print(facesVB1.shape)
print(facesVB1)
print("#####")
coordsVB2,facesVB2,volume_infoVB2,create_stampVB2 = nib.freesurfer.io.read_geometry("/NAS/tupac/romain/FS_VolBrain/FS60/bibiNew/surf//lh.smoothwm",True,True)
print(coordsVB2.shape)
print(coordsVB2)
print(facesVB2.shape)
print(facesVB2)

(151020, 3)
[[  -3.78306699 -102.45542145   21.19034195]
 [  -4.13593197 -102.56354523   21.00262451]
 [  -4.77936745 -102.45510864   21.0014019 ]
 ..., 
 [ -37.14464569   40.53471375    7.58266973]
 [ -38.79933929   41.66178513    8.10608006]
 [ -37.38536835   40.78133011    7.3743434 ]]
(302036, 3)
[[     0      1      4]
 [     5      4      1]
 [     0     45     46]
 ..., 
 [140266 140926 140925]
 [140266 140267 140257]
 [140903 140257 140915]]
#####
(151020, 3)
[[  -3.8458221  -101.92800903   21.12687302]
 [  -4.11440134 -101.95193481   21.01907539]
 [  -4.66071844 -101.85991669   21.10680199]
 ..., 
 [ -36.94448853   40.83981705    8.56929493]
 [ -38.58392715   42.00009155    8.71209049]
 [ -37.19326401   41.09831619    8.4027338 ]]
(302036, 3)
[[     0      1      4]
 [     5      4      1]
 [     0     45     46]
 ..., 
 [140266 140926 140925]
 [140266 140267 140257]
 [140903 140257 140915]]


In [266]:
curv=nib.freesurfer.io.read_morph_data("/NAS/tupac/romain/FS_VolBrain/FS60/bibiNew/surf//lh.curv")
print(curv.shape)
print(type(curv))
print(curv)

(151020,)
<type 'numpy.ndarray'>
[-0.30925533 -0.31436375 -0.30437082 ..., -0.2991145  -0.22383191
 -0.32259178]


In [277]:
coordsVB1,facesVB1,volume_infoVB1,create_stampVB1 = nib.freesurfer.io.read_geometry("/NAS/tupac/romain/FS_VolBrain/FS60/bibiNew/surf//lh.white",True,True)
print(coordsVB1.shape)
print(coordsVB1)
print(facesVB1.shape)
print(facesVB1)
print("#####")
coordsVB1,facesVB1,volume_infoVB1,create_stampVB1 = nib.freesurfer.io.read_geometry("/NAS/tupac/romain/FS_VolBrain/FS60/bibiNew/surf//lh.smoothwm",True,True)
print(coordsVB1.shape)
print(coordsVB1)
print(facesVB1.shape)
print(facesVB1)
print("#####")
coordsVB1,facesVB1,volume_infoVB1,create_stampVB1 = nib.freesurfer.io.read_geometry("/NAS/tupac/romain/FS_VolBrain/FS60/bibiNew/surf//lh.white.preaparc",True,True)
print(coordsVB1.shape)
print(coordsVB1)
print(facesVB1.shape)
print(facesVB1)
print("#####")
coordsVB1,facesVB1,volume_infoVB1,create_stampVB1 = nib.freesurfer.io.read_geometry("/NAS/tupac/romain/FS_VolBrain/FS60/bibiNew/surf//lh.sphere.reg",True,True)
print(coordsVB1.shape)
print(coordsVB1)
print(facesVB1.shape)
print(facesVB1)
print("#####")



(151020, 3)
[[  -3.78306699 -102.45542145   21.19034195]
 [  -4.13593197 -102.56354523   21.00262451]
 [  -4.77936745 -102.45510864   21.0014019 ]
 ..., 
 [ -37.14464569   40.53471375    7.58266973]
 [ -38.79933929   41.66178513    8.10608006]
 [ -37.38536835   40.78133011    7.3743434 ]]
(302036, 3)
[[     0      1      4]
 [     5      4      1]
 [     0     45     46]
 ..., 
 [140266 140926 140925]
 [140266 140267 140257]
 [140903 140257 140915]]
#####
(151020, 3)
[[  -3.8458221  -101.92800903   21.12687302]
 [  -4.11440134 -101.95193481   21.01907539]
 [  -4.66071844 -101.85991669   21.10680199]
 ..., 
 [ -36.94448853   40.83981705    8.56929493]
 [ -38.58392715   42.00009155    8.71209049]
 [ -37.19326401   41.09831619    8.4027338 ]]
(302036, 3)
[[     0      1      4]
 [     5      4      1]
 [     0     45     46]
 ..., 
 [140266 140926 140925]
 [140266 140267 140257]
 [140903 140257 140915]]
#####
(151020, 3)
[[  -3.81230974 -102.49047852   21.14514351]
 [  -4.16489887 -102.58